[project]
name = "nse-utility-reports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.1",
    "streamlit>=1.47.0",
]
